### ISSUE TITLE
Question about the manifests included in the sample applications

### ISSUE THREAD

**Issue by JCKrause** [aws-samples/appstream-serverless-image-creation-automation#1]
@JGrego-AWS First let me say that I am new to AppStream and this repo has saved me countless hours of work for which I am very thankful!

I have been working on deploying version 1.2 and I have noticed something in the sample application manifests that does not look quite right. In the PuTTYManifest.txt file there are two lines (76 and 123) that are for notepad++ and line 76 is not in the NotepadPPManifest.txt file.

76 c:\program files\notepad++\nppshell_06.dll
123 c:\windows\notepad.exe

If I am deploying just the Notepad++ application do I need to add line 76 to the NotepadPPManifest.txt file?

I am about to try deploying another application and I was wondering what is the best way to generate or create the manifest file?

Thanks,
John

**Comment by JGrego-AWS** [comment]
@JCKrause I am glad this has been helpful!

With regards to the manifests, I just pushed an update to the NPP manifest as a better example of how it should look. 

Just as a quick background since you are new to AppStream, the manifest file is a list of files that the service touches to "prewarm" them when a new instance is added to your fleet and the EBS snapshot is rehydrated. Essentially what this does is improve the launch performance of the application for your users. Ideally, it contains all the files required to launch your application to ensure they are loaded first. Without it, everything will function just fine, it may just launch slightly slower. Here are some links to more information in the official documentation:

- [https://docs.aws.amazon.com/appstream2/latest/developerguide/programmatically-create-image.html#optimize-app-launch-performance-image-assistant-cli](url)
- https://docs.aws.amazon.com/appstream2/latest/developerguide/customizing-appstream-images.html#optimizing-app-launch-performance
